lib/task_manager_web/router.ex
defmodule TaskManager2Web.Router do
  use TaskManager2Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskManager2Web.Plugs.FetchSession
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskManager2Web.Plugs.FetchSession
  end

  scope "/", TaskManager2Web do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/assigns", AssignController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax/", TaskManager2Web do
    resources "/time_blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskManager2Web do
  #   pipe_through :api
  # end
end

lib/task_manager_web/views/layout_view.ex
defmodule TaskManager2Web.LayoutView do
  use TaskManager2Web, :view
end

lib/task_manager_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TaskManager2</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-light bg-white">
        <div class="col-3">
		<!-- <a class="navbar-brand title" href="">Task Manager</a> -->
	  <%= link "Task Manager", to: Routes.page_path(@conn, :index), class: "navbar-brand title" %>
	</div>
	<div class="col-6">

	  <ul class="navbar-nav mr-auto">
            <%= if @current_user do %>
            <li class="nav-item">
              <a href="<%= Routes.page_path(@conn, :index) %>" class="nav-link">My Tasks</a>
            </li>
            <% end %>
	    <li class="nav-item">
	      <a href="<%= Routes.task_path(@conn, :index) %>" class="nav-link">Tasks</a>
	    </li>
	    <li class="nav-item">
	      <a href="<%= Routes.assign_path(@conn, :index) %>" class="nav-link">In Progress</a>
	    </li>
            <%= if @current_user && TaskManager2Web.PageView.is_manager?(Plug.Conn.get_session(@conn, :user_id)) do %>
            <li class="nav-item">
              <a href="<%= Routes.user_path(@conn, :index) %>" class="nav-link">Edit Users</a>
            </li>
            <% end %>
	  </ul>
	</div>
	<div class="col-3">
	  <%= if @current_user do %>
	    <p class="my-3">
	      User: <%= @current_user.name %> <%= link "Logout", to: Routes.session_path(@conn, :delete), method: :delete %>
	    </p>
	  <% else %>
	    <%= form_for @conn, Routes.session_path(@conn, :create),
	             [class: "form-inline"], fn f -> %>
	      <%= text_input f, :email, class: "form-control" %>
	      <%= submit "Login", class: "btn btn-secondary" %>
	    <% end %>
	  <% end %>
	</div>
      </nav>

      <div class="row">
	<div class="col-12">
	  <%= if get_flash(@conn, :info) do %>
	    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
	  <% end %>
	  <%= if get_flash(@conn, :error) do %>
	    <p class="alert alert-danger" role="alert">
	      <% get_flash(@conn, :error) %>
	    </p>
	  <% end %>
	</div>
      </div>
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>